### ISSUE TITLE
Add BigUint overloads for == + - * / for common primitive types like Uint8 / Uint16 / Uint32 / Uint64 / integerLiteral

### ISSUE THREAD

**Issue by janniksam** [gfusee/space#43]

**Comment by gfusee** [comment]
you can keep track of the progress in [feature/biguint_integer_operators](https://github.com/gfusee/space/tree/feature/biguint_integer_operators)

**Comment by gfusee** [comment]
After some researches, overloading those operators disables the ability to do the native ones.

For instance, if we assume myInteger to be a UInt8, then both 1 + myInteger no longer compile because of the confusion between BigUint + UInt8 and UInt8 + UInt8. This is the same for myInteger + 1 and to all the other operators.
